### ISSUE TITLE
Consider alpine/busybox base image

### ISSUE THREAD

**Issue by tracker1** [andredumas/docker-travis-ci-cli#1]
https://github.com/gliderlabs/docker-alpine

Should save quite a bit of space over the ubuntu 14:04 base.

**Comment by andredumas** [comment]
Nice thanks for the suggestion. That is a huge difference.

**Comment by antonmry** [comment]
I started to work on this: https://github.com/antonmry/docker-travis-ci-cli/tree/Alpine-Linux but I'm blocked by https://github.com/ffi/ffi/issues/485

I will update and create PR as soon as the issue is solved.

**Comment by antonmry** [comment]
Issue fixed and image created and working. PR here: https://github.com/andredumas/docker-travis-ci-cli/pull/3

From 419,5 MB to 148 MB. It's on Docker Hub if you want to test it: https://hub.docker.com/r/antonmry/travis-docker/
