### ISSUE TITLE
Outdated travis version in image

### ISSUE THREAD

**Issue by phillipgreenii** [andredumas/docker-travis-ci-cli#2]
Please rebuild and push the docker image.  Currently, travis fails unless the image is re-built.

**Comment by andredumas** [comment]
I've rebuilt it. Haven't had a chance to retest it, but I would think installed via package managers it should be ok.

https://registry.hub.docker.com/u/andredumas/travis-ci-cli/build_id/13593/code/bfswxutkgxzhlzhg6njqvse/

```
.
.
.
Successfully installed travis-1.7.6
.
.
.
```
